### PR TITLE
Bump Ruby from 2.7.2 to 2.7.3

### PR DESCRIPTION
**Pull request by denny**
Also picked up the 'mimemagic is missing' stuff in this, and the accompanying patch bump in Rails, so quite a lot of Gemfile activity.

### CODE REVIEW

**Comment by denny** [comment]
Can anybody reviewing this pay close attention to the omniauth stuff please? There was a conflict around the repost gem in the Gemfile.

**Review by jkhulme — CHANGES_REQUESTED** [review]
It looks good, I think the omniauth/repost stuff looks fine still as well.
I think this PR just needs to update CI config as well - which is still running against ruby 2.7.1

**Comment by denny** [comment]
> It looks good, I think the omniauth/repost stuff looks fine still as well.
> I think this PR just needs to update CI config as well - which is still running against ruby 2.7.1

Just spotted this, should be done now.

**Comment by denny** [comment]
Hrm, doesn't seem to be picking up that change, I'm going to kill this PR and start another one...

**Pull request closed without merging**
